import argparse
import json
import os
from pathlib import Path


DIFFICULTY_FILES = {
    "easy": "easy.txt",
    "medium": "medium.txt",
    "hard": "hard.txt",
    "diabolical": "diabolical.txt",
}


def iter_puzzles(path: Path):
    with path.open("r", encoding="utf-8", newline="") as f:
        for line in f:
            s = line.strip()
            if not s:
                continue
            parts = s.split()
            if len(parts) < 2:
                continue
            puzzle = parts[1]
            if len(puzzle) != 81 or any(ch not in "0123456789" for ch in puzzle):
                continue
            yield puzzle


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bank",
        default=str(Path(__file__).resolve().parents[2] / "sudoku-exchange-puzzle-bank-master"),
        help="Path to sudoku-exchange-puzzle-bank-master",
    )
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parents[1] / "levels.js"),
        help="Output levels.js path",
    )
    parser.add_argument("--limit", type=int, default=2000)
    args = parser.parse_args()

    bank = Path(args.bank)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    packed = {}
    for diff, filename in DIFFICULTY_FILES.items():
        p = bank / filename
        if not p.exists():
            raise SystemExit(f"Missing bank file: {p}")
        puzzles = []
        for i, puzzle in enumerate(iter_puzzles(p)):
            puzzles.append(puzzle)
            if args.limit and (i + 1) >= args.limit:
                break
        data = "".join(puzzles)
        packed[diff] = {"count": len(puzzles), "data": data}

    banner = (
        "/* Auto-generated by tools/build_levels.py. "
        "Re-run to refresh bundled puzzle subset. */\n"
    )
    payload = json.dumps(packed, ensure_ascii=False, separators=(",", ":"))
    content = banner + "window.SUDOKU_LEVEL_DATA=" + payload + ";\n"
    out.write_text(content, encoding="utf-8", newline="\n")

    print(f"Wrote {out}")
    for diff, obj in packed.items():
        print(f"{diff}: {obj['count']} puzzles, {len(obj['data'])} chars")


if __name__ == "__main__":
    main()

